### PR TITLE
Add an option to send request and response as a single message

### PR DESCRIPTION
**Pull request by jbuck**
Fixes issue #3.

### CODE REVIEW

**Comment by brianloveswords** [comment]
HEYYYYY sorry I missed this! Can you also add something to the README.md explaining this option?!

**Comment by jbuck** [comment]
Yep!

**Comment by jbuck** [comment]
doneski

**Comment by brianloveswords** [comment]
You are a legendary hero.

**Comment by brianloveswords** [comment]
Added you as a collaborator on both github and npm, feel free to publish a new version!

**Pull request merged**
